import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./custom-components/Navbar";
import ContactHeader from "./custom-components/ContactHeader";
import Contact from "./custom-components/Contact";
import NewsLetter from "./custom-components/NewsLetter";
import Footer from "./custom-components/Footer";

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased w-full`}
      >
        <ContactHeader />
        <Navbar />
        {children}
        <div className="relative">
          <Contact />
          <NewsLetter />
        </div>
        <Footer />
      </body>
    </html>
  );
}
